backend:
  name: git-gateway
  branch: master
media_folder: static/images
public_folder: /images
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "type", label: "Type", widget: "hidden", default: "blog" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "cover", label: "Cover", widget: "image" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "Body", label: "body", widget: "markdown" }