backend:
  name: git-gateway
  branch: master
media_folder: static/images
public_folder: /images
collections:
  - name: "deals"
    label: "Deals"
    folder: "src/pages/blog/deals"
    create: true
    editor:
     preview: false
    slug: "{{slug}}"
    fields:
      - { name: "type", label: "Type", widget: "hidden", default: "deals" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "cover", label: "Cover", widget: "image" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "deal", label: "Link To Deal", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
  - name: "howto"
    label: "How To"
    folder: "src/pages/blog/howto"
    create: true
    editor:
     preview: false
    slug: "{{slug}}"
    fields:
      - { name: "type", label: "Type", widget: "hidden", default: "howto" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "cover", label: "Cover", widget: "image" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
  - name: "news"
    label: "News"
    folder: "src/pages/blog/news"
    create: true
    editor:
     preview: false
    slug: "{{slug}}"
    fields:
      - { name: "type", label: "Type", widget: "hidden", default: "news" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "cover", label: "Cover", widget: "image" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }